# netlify.toml

[build]
# Your site is static HTML/CSS/JS in the repo root
publish = "."

# If you have no build step, omit "command"
# command = ""

[build.environment]
NODE_VERSION = "20"

[build]
publish = "."