[build]
publish = "."
command = ""

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[build.environment]
NODE_VERSION = "18"

# Route API calls to the function
[[redirects]]
from = "/api/ai"
to = "/.netlify/functions/ai"
status = 200

# Then handle SPA fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200